-- Stargate Blog Hub feedback, survey and community schema
-- Run once in the Supabase SQL Editor for project inftexpcnfinglwlrvsj.
create extension if not exists pgcrypto;
create table if not exists public.blog_reactions(id uuid primary key default gen_random_uuid(),target_type text not null check(char_length(target_type) between 1 and 40),target_id text not null check(char_length(target_id) between 1 and 160),visitor_id uuid not null,liked boolean not null default false,rating smallint check(rating between 1 and 5),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(target_type,target_id,visitor_id));
create table if not exists public.survey_responses(id uuid primary key default gen_random_uuid(),visitor_id uuid not null,topics text[] not null check(cardinality(topics) between 1 and 8),recommend_score smallint not null check(recommend_score between 0 and 10),comment text check(char_length(comment)<=500),source text check(char_length(source)<=120),created_at timestamptz not null default now());
create table if not exists public.board_posts(id uuid primary key default gen_random_uuid(),visitor_id uuid not null,nickname text not null check(char_length(nickname) between 1 and 24),title text not null check(char_length(title) between 1 and 100),content text not null check(char_length(content) between 1 and 2000),category text not null default '자유' check(category in('자유','질문','후기','건의','공지')),is_hidden boolean not null default false,comment_count integer not null default 0 check(comment_count>=0),report_count integer not null default 0 check(report_count>=0),created_at timestamptz not null default now());
create table if not exists public.board_comments(id uuid primary key default gen_random_uuid(),post_id uuid not null references public.board_posts(id) on delete cascade,visitor_id uuid not null,nickname text not null check(char_length(nickname) between 1 and 24),content text not null check(char_length(content) between 1 and 500),is_hidden boolean not null default false,report_count integer not null default 0 check(report_count>=0),created_at timestamptz not null default now());
create table if not exists public.board_reports(id uuid primary key default gen_random_uuid(),target_type text not null check(target_type in('post','comment')),target_id uuid not null,visitor_id uuid not null,reason text not null default '사용자 신고' check(char_length(reason)<=200),created_at timestamptz not null default now(),unique(target_type,target_id,visitor_id));
create index if not exists board_posts_created_at_idx on public.board_posts(created_at desc) where is_hidden=false;
create index if not exists board_comments_post_id_idx on public.board_comments(post_id,created_at) where is_hidden=false;
create index if not exists blog_reactions_target_idx on public.blog_reactions(target_type,target_id);
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;
drop trigger if exists blog_reactions_touch_updated_at on public.blog_reactions;
create trigger blog_reactions_touch_updated_at before update on public.blog_reactions for each row execute function public.touch_updated_at();
create or replace function public.sync_comment_count() returns trigger language plpgsql security definer set search_path=public as $$begin if tg_op='INSERT' then update public.board_posts set comment_count=comment_count+1 where id=new.post_id;return new;elsif tg_op='DELETE' then update public.board_posts set comment_count=greatest(comment_count-1,0) where id=old.post_id;return old;end if;return null;end;$$;
drop trigger if exists board_comments_sync_count on public.board_comments;
create trigger board_comments_sync_count after insert or delete on public.board_comments for each row execute function public.sync_comment_count();
create or replace function public.apply_report() returns trigger language plpgsql security definer set search_path=public as $$begin if new.target_type='post' then update public.board_posts set report_count=report_count+1,is_hidden=case when report_count+1>=3 then true else is_hidden end where id=new.target_id;elsif new.target_type='comment' then update public.board_comments set report_count=report_count+1,is_hidden=case when report_count+1>=3 then true else is_hidden end where id=new.target_id;end if;return new;end;$$;
drop trigger if exists board_reports_apply on public.board_reports;
create trigger board_reports_apply after insert on public.board_reports for each row execute function public.apply_report();
alter table public.blog_reactions enable row level security;
alter table public.survey_responses enable row level security;
alter table public.board_posts enable row level security;
alter table public.board_comments enable row level security;
alter table public.board_reports enable row level security;
drop policy if exists "public read reactions" on public.blog_reactions;create policy "public read reactions" on public.blog_reactions for select to anon,authenticated using(true);
drop policy if exists "public insert reactions" on public.blog_reactions;create policy "public insert reactions" on public.blog_reactions for insert to anon,authenticated with check(true);
drop policy if exists "public update reactions" on public.blog_reactions;create policy "public update reactions" on public.blog_reactions for update to anon,authenticated using(true) with check(true);
drop policy if exists "public submit surveys" on public.survey_responses;create policy "public submit surveys" on public.survey_responses for insert to anon,authenticated with check(true);
drop policy if exists "public read visible posts" on public.board_posts;create policy "public read visible posts" on public.board_posts for select to anon,authenticated using(is_hidden=false);
drop policy if exists "public create posts" on public.board_posts;create policy "public create posts" on public.board_posts for insert to anon,authenticated with check(category<>'공지' and is_hidden=false and comment_count=0 and report_count=0);
drop policy if exists "public read visible comments" on public.board_comments;create policy "public read visible comments" on public.board_comments for select to anon,authenticated using(is_hidden=false);
drop policy if exists "public create comments" on public.board_comments;create policy "public create comments" on public.board_comments for insert to anon,authenticated with check(is_hidden=false and report_count=0);
drop policy if exists "public create reports" on public.board_reports;create policy "public create reports" on public.board_reports for insert to anon,authenticated with check(true);
grant usage on schema public to anon,authenticated;
grant select,insert,update on public.blog_reactions to anon,authenticated;
grant insert on public.survey_responses to anon,authenticated;
grant select,insert on public.board_posts to anon,authenticated;
grant select,insert on public.board_comments to anon,authenticated;
grant insert on public.board_reports to anon,authenticated;